[package]
name = "Vodeo2ASCII"
version = "0.2.0"
edition = "2021"

[dependencies]
crossterm = "0.28"
image = "0.25"
anyhow = "1.0"
inquire = "0.7"
glob = "0.3"
regex = "1.10"
ratatui = "0.29.0"
sysinfo = "0.33.1"
chrono = "0.4" # For time display